# Generated by Django 5.2.6 on 2025-10-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.CharField(default='BASIC', max_length=10),
        ),
    ]
