# Generated by Django for manual M-Pesa integration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_remove_payment_course_alter_payment_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("mpesa", "M-Pesa"),
                    ("stripe", "Stripe"),
                    ("manual_mpesa", "Manual M-Pesa"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="mpesa_receipt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
