# Generated by Django 5.2.6 on 2025-11-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_manual_mpesa_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa_stk', 'M-Pesa STK Push (Lipana)'), ('mpesa', 'M-Pesa (Legacy STK)'), ('stripe', 'Stripe'), ('manual_mpesa', 'Manual M-Pesa')], max_length=15),
        ),
    ]
