BEGIN;
--
-- Add field color to course
--
ALTER TABLE "courses_course" ADD COLUMN "color" varchar(10) DEFAULT '#e63946' NOT NULL;
ALTER TABLE "courses_course" ALTER COLUMN "color" DROP DEFAULT;
--
-- Add field created_by to course
--
ALTER TABLE "courses_course" ADD COLUMN "created_by_id" bigint NULL CONSTRAINT "courses_course_created_by_id_4c488f66_fk_accounts_user_id" REFERENCES "accounts_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "courses_course_created_by_id_4c488f66_fk_accounts_user_id" IMMEDIATE;
--
-- Add field domain to course
--
ALTER TABLE "courses_course" ADD COLUMN "domain" varchar(20) DEFAULT 'cybersecurity' NOT NULL;
ALTER TABLE "courses_course" ALTER COLUMN "domain" DROP DEFAULT;
--
-- Add field icon to course
--
ALTER TABLE "courses_course" ADD COLUMN "icon" varchar(10) DEFAULT '💻' NOT NULL;
ALTER TABLE "courses_course" ALTER COLUMN "icon" DROP DEFAULT;
--
-- Add field is_published to course
--
ALTER TABLE "courses_course" ADD COLUMN "is_published" boolean DEFAULT false NOT NULL;
ALTER TABLE "courses_course" ALTER COLUMN "is_published" DROP DEFAULT;
--
-- Add field has_lab to lesson
--
ALTER TABLE "courses_lesson" ADD COLUMN "has_lab" boolean DEFAULT true NOT NULL;
ALTER TABLE "courses_lesson" ALTER COLUMN "has_lab" DROP DEFAULT;
--
-- Add field icon to lesson
--
ALTER TABLE "courses_lesson" ADD COLUMN "icon" varchar(10) DEFAULT '📖' NOT NULL;
ALTER TABLE "courses_lesson" ALTER COLUMN "icon" DROP DEFAULT;
--
-- Add field is_published to lesson
--
ALTER TABLE "courses_lesson" ADD COLUMN "is_published" boolean DEFAULT false NOT NULL;
ALTER TABLE "courses_lesson" ALTER COLUMN "is_published" DROP DEFAULT;
--
-- Add field lab_language to lesson
--
ALTER TABLE "courses_lesson" ADD COLUMN "lab_language" varchar(20) DEFAULT '' NOT NULL;
ALTER TABLE "courses_lesson" ALTER COLUMN "lab_language" DROP DEFAULT;
--
-- Add field lesson_type to lesson
--
ALTER TABLE "courses_lesson" ADD COLUMN "lesson_type" varchar(20) DEFAULT 'drill' NOT NULL;
ALTER TABLE "courses_lesson" ALTER COLUMN "lesson_type" DROP DEFAULT;
--
-- Add field notebook_filename to lesson
--
ALTER TABLE "courses_lesson" ADD COLUMN "notebook_filename" varchar(200) DEFAULT '' NOT NULL;
ALTER TABLE "courses_lesson" ALTER COLUMN "notebook_filename" DROP DEFAULT;
--
-- Add field starter_code to lesson
--
ALTER TABLE "courses_lesson" ADD COLUMN "starter_code" text DEFAULT '' NOT NULL;
ALTER TABLE "courses_lesson" ALTER COLUMN "starter_code" DROP DEFAULT;
--
-- Add field terminal_commands to lesson
--
ALTER TABLE "courses_lesson" ADD COLUMN "terminal_commands" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE "courses_lesson" ALTER COLUMN "terminal_commands" DROP DEFAULT;
--
-- Add field theory_html to lesson
--
ALTER TABLE "courses_lesson" ADD COLUMN "theory_html" text DEFAULT '' NOT NULL;
ALTER TABLE "courses_lesson" ALTER COLUMN "theory_html" DROP DEFAULT;
--
-- Add field xp_reward to lesson
--
ALTER TABLE "courses_lesson" ADD COLUMN "xp_reward" integer DEFAULT 50 NOT NULL;
ALTER TABLE "courses_lesson" ALTER COLUMN "xp_reward" DROP DEFAULT;
--
-- Alter field lab_config on lesson
--
-- (no-op)
--
-- Create model Drill
--
CREATE TABLE "courses_drill" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "order" integer NOT NULL CHECK ("order" >= 0), "prompt" varchar(100) NOT NULL, "task" text NOT NULL, "hint" text NOT NULL, "lesson_id" bigint NOT NULL);
--
-- Create model DrillAnswer
--
CREATE TABLE "courses_drillanswer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "answer" varchar(500) NOT NULL, "is_case_sensitive" boolean NOT NULL, "drill_id" bigint NOT NULL);
--
-- Create model Level
--
CREATE TABLE "courses_level" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "slug" varchar(50) NOT NULL, "level_type" varchar(20) NOT NULL, "description" text NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "is_published" boolean NOT NULL, "course_id" bigint NOT NULL);
--
-- Create model Module
--
CREATE TABLE "courses_module" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "description" text NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "icon" varchar(10) NOT NULL, "color" varchar(10) NOT NULL, "xp_reward" integer NOT NULL, "is_published" boolean NOT NULL, "single_module_price" numeric(8, 2) NOT NULL, "level_id" bigint NOT NULL);
--
-- Add field module to lesson
--
ALTER TABLE "courses_lesson" ADD COLUMN "module_id" bigint NULL CONSTRAINT "courses_lesson_module_id_41252914_fk_courses_module_id" REFERENCES "courses_module"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "courses_lesson_module_id_41252914_fk_courses_module_id" IMMEDIATE;
--
-- Create model Quiz
--
CREATE TABLE "courses_quiz" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "question" text NOT NULL, "explanation" text NOT NULL, "lesson_id" bigint NOT NULL UNIQUE);
--
-- Create model QuizOption
--
CREATE TABLE "courses_quizoption" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "label" varchar(1) NOT NULL, "text" text NOT NULL, "is_correct" boolean NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "quiz_id" bigint NOT NULL);
CREATE INDEX "courses_course_created_by_id_4c488f66" ON "courses_course" ("created_by_id");
ALTER TABLE "courses_drill" ADD CONSTRAINT "courses_drill_lesson_id_1744d13a_fk_courses_lesson_id" FOREIGN KEY ("lesson_id") REFERENCES "courses_lesson" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "courses_drill_lesson_id_1744d13a" ON "courses_drill" ("lesson_id");
ALTER TABLE "courses_drillanswer" ADD CONSTRAINT "courses_drillanswer_drill_id_ba0431b7_fk_courses_drill_id" FOREIGN KEY ("drill_id") REFERENCES "courses_drill" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "courses_drillanswer_drill_id_ba0431b7" ON "courses_drillanswer" ("drill_id");
ALTER TABLE "courses_level" ADD CONSTRAINT "courses_level_course_id_slug_06a523e1_uniq" UNIQUE ("course_id", "slug");
ALTER TABLE "courses_level" ADD CONSTRAINT "courses_level_course_id_f00dfb69_fk_courses_course_id" FOREIGN KEY ("course_id") REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "courses_level_slug_085a8090" ON "courses_level" ("slug");
CREATE INDEX "courses_level_slug_085a8090_like" ON "courses_level" ("slug" varchar_pattern_ops);
CREATE INDEX "courses_level_course_id_f00dfb69" ON "courses_level" ("course_id");
ALTER TABLE "courses_module" ADD CONSTRAINT "courses_module_level_id_81be9927_fk_courses_level_id" FOREIGN KEY ("level_id") REFERENCES "courses_level" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "courses_module_level_id_81be9927" ON "courses_module" ("level_id");
CREATE INDEX "courses_lesson_module_id_41252914" ON "courses_lesson" ("module_id");
ALTER TABLE "courses_quiz" ADD CONSTRAINT "courses_quiz_lesson_id_2bf49392_fk_courses_lesson_id" FOREIGN KEY ("lesson_id") REFERENCES "courses_lesson" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "courses_quizoption" ADD CONSTRAINT "courses_quizoption_quiz_id_6ec810d2_fk_courses_quiz_id" FOREIGN KEY ("quiz_id") REFERENCES "courses_quiz" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "courses_quizoption_quiz_id_6ec810d2" ON "courses_quizoption" ("quiz_id");
COMMIT;
