# Generated by Django 5.2.8 on 2026-02-26 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_coderevision_conversationmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="websiteorder",
            name="ai_project_type",
            field=models.CharField(
                choices=[
                    ("single_file", "Single HTML File"),
                    ("multi_file", "HTML/CSS/JS Separate"),
                    ("react", "React Project"),
                ],
                default="single_file",
                help_text="Type of project structure for AI generation",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("js", "JavaScript"),
                            ("jsx", "JSX/React"),
                            ("ts", "TypeScript"),
                            ("tsx", "TSX/React"),
                            ("json", "JSON"),
                            ("md", "Markdown"),
                            ("other", "Other"),
                        ],
                        default="html",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("is_entry_point", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_files",
                        to="services.websiteorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_entry_point", "filename"],
                "indexes": [
                    models.Index(
                        fields=["order", "file_type"],
                        name="services_pr_order_i_a63cd1_idx",
                    )
                ],
                "unique_together": {("order", "filename")},
            },
        ),
    ]
