# Generated by Django 5.2.8 on 2026-02-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_websiteorder_ai_project_type_projectfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="websiteorder",
            name="generated_zip",
            field=models.FileField(
                blank=True, null=True, upload_to="ai_generated_projects/zips/"
            ),
        ),
    ]
