# Generated by Django 5.2.8 on 2026-03-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_websiteorder_generated_zip"),
    ]

    operations = [
        migrations.AddField(
            model_name="websiteorder",
            name="is_ai_sandbox",
            field=models.BooleanField(
                default=False,
                help_text="If True, this is an AI project that hasn't been converted to a formal order yet",
            ),
        ),
    ]
