# Generated by Django 5.2.8 on 2026-03-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_websiteorder_is_ai_sandbox"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationmessage",
            name="order",
        ),
        migrations.AlterUniqueTogether(
            name="projectfile",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="projectfile",
            name="order",
        ),
        migrations.DeleteModel(
            name="CodeRevision",
        ),
        migrations.DeleteModel(
            name="ConversationMessage",
        ),
        migrations.DeleteModel(
            name="ProjectFile",
        ),
    ]
