# Generated by Django 5.2.8 on 2026-03-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_remove_conversationmessage_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websiterevision",
            name="order",
        ),
        migrations.DeleteModel(
            name="WebsiteOrder",
        ),
        migrations.DeleteModel(
            name="WebsiteRevision",
        ),
    ]
