# Generated by Django 5.2.6 on 2025-11-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('student', 'student'), ('management', 'management')], default='student', max_length=20),
        ),
    ]
