# Generated by Django 5.2.8 on 2026-02-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_activitylog_loginattempt_failure_reason"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="accounts_ac_timesta_ffc3ad_idx",
            old_name="accounts_ac_timesta_04c55a_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="accounts_ac_action_fde492_idx",
            old_name="accounts_ac_action_28f244_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="accounts_ac_severit_78548c_idx",
            old_name="accounts_ac_severit_323212_idx",
        ),
        migrations.RenameIndex(
            model_name="activitylog",
            new_name="accounts_ac_user_id_9bf4ca_idx",
            old_name="accounts_ac_user_id_4719b6_idx",
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["-timestamp"], name="accounts_lo_timesta_59ffc2_idx"
            ),
        ),
    ]
