# Generated by Django 5.2.8 on 2026-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_rename_accounts_ac_timesta_04c55a_idx_accounts_ac_timesta_ffc3ad_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("staff", "staff"),
                    ("student", "student"),
                    ("management", "management"),
                    ("client", "client"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
