# Generated by Django 5.2.8 on 2026-03-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.CharField(default="NEWBIE", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="streak_days",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="total_xp",
            field=models.IntegerField(default=0),
        ),
    ]
