# Generated by Django 5.2.6 on 2025-10-26 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('unlocked_lessons_count', models.PositiveIntegerField(default=2, help_text='Number of lessons unlocked for this plan (free plan typically unlocks first 2 lessons)')),
                ('can_access_quizzes', models.BooleanField(default=False)),
                ('can_access_projects', models.BooleanField(default=False)),
                ('can_access_certificates', models.BooleanField(default=False)),
                ('can_access_live_classes', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('text', 'Text Answer'), ('code', 'Code Answer')], max_length=20)),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.quizquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('week_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='courses.course')),
            ],
            options={
                'ordering': ['level', 'week_number'],
                'unique_together': {('course', 'level', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('content', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('duration', models.IntegerField(default=0, help_text='Lesson duration in minutes')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.week')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('week', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectives', models.TextField(help_text='Learning objectives for this project')),
                ('requirements', models.TextField(help_text='Project requirements and deliverables')),
                ('resources', models.TextField(blank=True, help_text='Recommended resources and tools')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('estimated_hours', models.PositiveIntegerField(default=4, help_text='Estimated time to complete in hours')),
                ('submission_instructions', models.TextField(help_text='How to submit the project')),
                ('is_active', models.BooleanField(default=True)),
                ('week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_project', to='courses.week')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Weekly Quiz', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('time_limit', models.PositiveIntegerField(default=60, help_text='Time limit in minutes for the weekly quiz')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Passing score percentage')),
                ('total_questions', models.PositiveIntegerField(default=30, help_text='Total number of questions in the weekly quiz')),
                ('is_active', models.BooleanField(default=True)),
                ('week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_quiz', to='courses.week')),
            ],
            options={
                'verbose_name_plural': 'Weekly Quizzes',
            },
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='weekly_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.weeklyquiz'),
        ),
        migrations.CreateModel(
            name='WeeklyQuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Time taken in seconds')),
                ('passed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_quiz_submissions', to=settings.AUTH_USER_MODEL)),
                ('weekly_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.weeklyquiz')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'weekly_quiz')},
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro')], default='FREE', max_length=10)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.week')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'week')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('quiz_completed', models.BooleanField(default=False)),
                ('project_completed', models.BooleanField(default=False)),
                ('week_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to='courses.week')),
            ],
            options={
                'verbose_name_plural': 'Weekly progress',
                'unique_together': {('user', 'week')},
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_url', models.URLField(help_text='URL to the project repository or demo')),
                ('description', models.TextField(help_text="Student's description of their project")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_feedback', models.TextField(blank=True)),
                ('score', models.PositiveIntegerField(blank=True, help_text='Score out of 100', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
                ('weekly_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.weeklyproject')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'weekly_project')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quizquestion')),
                ('selected_choices', models.ManyToManyField(blank=True, to='courses.questionchoice')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.weeklyquizsubmission')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
