# Generated by Django 5.2.6 on 2025-10-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='code_sniplet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_url',
            field=models.URLField(blank=True),
        ),
    ]
