# Generated by Django 5.2.6 on 2025-10-27 00:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_notification_projectfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='project_submissions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='submission_url',
            field=models.URLField(blank=True, help_text='URL to the project repository or demo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
