# Generated by Django 5.2.6 on 2025-10-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_projectsubmission_submission_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='description',
            field=models.TextField(blank=True, help_text="Student's description of their project", null=True),
        ),
    ]
