# Generated by Django 5.2.6 on 2025-10-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_projectsubmission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyquizsubmission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
