# Generated by Django 5.2.6 on 2025-10-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_weeklyquizsubmission_attempt_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyquizsubmission',
            unique_together=set(),
        ),
    ]
