# Generated by Django 5.2.6 on 2025-10-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_weeklyquizsubmission_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
