# Generated by Django manually
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_course_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="last_accessed",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
