# Generated by Django 5.2.8 on 2026-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_alter_course_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lab_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration for the lab environment (e.g., {'initial_code': '...', 'language': 'python'})",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lab_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("ide", "IDE (Code Editor)"),
                    ("terminal", "Terminal (Linux/Kali)"),
                    ("wasm", "WebAssembly (Browser Execution)"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
