# Generated by Django 5.2.8 on 2026-03-08 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_lesson_lab_config_lesson_lab_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="color",
            field=models.CharField(default="#e63946", max_length=10),
        ),
        migrations.AddField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="domain",
            field=models.CharField(
                choices=[
                    ("cybersecurity", "Cybersecurity"),
                    ("programming", "Programming"),
                    ("ai_ml", "AI & Machine Learning"),
                ],
                default="cybersecurity",
                help_text="Determines the lab environment for all lessons in this course",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="icon",
            field=models.CharField(default="💻", max_length=10),
        ),
        migrations.AddField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="has_lab",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="icon",
            field=models.CharField(default="📖", max_length=10),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lab_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("java", "Java"),
                    ("c", "C"),
                    ("cpp", "C++"),
                ],
                help_text="Only used when course domain is programming",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("drill", "Terminal/Code Drill"),
                    ("reading", "Reading + Theory"),
                    ("video", "Video"),
                    ("lab", "Full Lab"),
                ],
                default="drill",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="notebook_filename",
            field=models.CharField(
                blank=True,
                help_text="Filename of .ipynb in JupyterLite content dir. Only for ai_ml courses.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="starter_code",
            field=models.TextField(
                blank=True, help_text="Starter code shown in editor"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="terminal_commands",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra command:response pairs for the terminal simulation in this lesson",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="theory_html",
            field=models.TextField(
                blank=True, help_text="HTML content — supports inline code highlighting"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="xp_reward",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lab_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration for the lab environment",
            ),
        ),
        migrations.CreateModel(
            name="Drill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("prompt", models.CharField(default="$", max_length=100)),
                ("task", models.TextField()),
                ("hint", models.TextField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drills",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DrillAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=500)),
                ("is_case_sensitive", models.BooleanField(default=False)),
                (
                    "drill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="courses.drill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                (
                    "level_type",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("course", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("icon", models.CharField(default="📦", max_length=10)),
                ("color", models.CharField(default="#48cae4", max_length=10)),
                ("xp_reward", models.IntegerField(default=50)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "single_module_price",
                    models.DecimalField(decimal_places=2, default=299.0, max_digits=8),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.level",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.module",
            ),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("explanation", models.TextField()),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="courses.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=1)),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="courses.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
