# Generated by Django 5.2.8 on 2026-03-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_course_color_course_created_by_course_domain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="week",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.week",
            ),
        ),
    ]
