# Generated by Django 5.2.8 on 2026-03-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_alter_lesson_slug_alter_lesson_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="level",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="module",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
