# Generated by Django 5.2.8 on 2026-03-12 21:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0016_alter_course_is_published_alter_lesson_is_published_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="drill",
            name="hint",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="drill",
            name="task",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="LessonMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="hub/lesson_media/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "svg",
                                    "webp",
                                ]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="courses.lesson",
                    ),
                ),
            ],
        ),
    ]
