import json
import logging
import uuid
from typing import Dict, Any, Generator
from ..ai.stepfun_client import OpenRouterBuilderClient

logger = logging.getLogger(__name__)

class AgentOrchestrator:
    # Future: In-memory store for WebContainers or E2B sessions
    active_sessions: Dict[str, Any] = {}

    def __init__(self, session_id: str = None):
        self.session_id = session_id or str(uuid.uuid4())
        
    def _sse(self, payload: dict) -> str:
        return f"data: {json.dumps(payload)}\n\n"

    def stream_build(self, prompt: str, model_name: str, existing_files=None, is_chat=False) -> Generator[str, None, None]:
        """
        Orchestrates AI generation. WebContainer/E2B logic will be added here.
        Yields SSE formatted strings.
        """
        yield self._sse({"status": "Initializing agent orchestrator..."})

        # 1. AI Generation Stream
        client = OpenRouterBuilderClient(model=model_name)
        generated_files = []
        
        # We reuse the stream_generation from our openrouter client
        # It yields chunk, thinking, progress events directly.
        for event in client.stream_generation(
            prompt, 
            existing_files=existing_files, 
            output_type="react", 
            suppress_done=True
        ):
            if event.startswith("data: "):
                try:
                    payload = json.loads(event[6:].strip())
                    if "files" in payload:
                        generated_files = payload["files"]
                    
                    # ALWAYS yield the event immediately to the frontend
                    yield event
                except json.JSONDecodeError:
                    yield event
            else:
                # Heartbeats (spaces) or other raw data
                yield event

        if not generated_files:
            yield self._sse({"error": "No files were generated by the AI."})
            return

        # 2. Placeholder for Environment Setup (WebContainer/E2B)
        yield self._sse({"status": "Finalizing build..."})

        yield self._sse({
            "complete": True,
            "summary": "AI Generation complete! Deployment coming soon.",
            "files": generated_files,
            "session_id": self.session_id
        })

    def cleanup(self):
        """Cleanup session resources."""
        if self.session_id in self.active_sessions:
            logger.info(f"Cleaning up session {self.session_id}")
            # Placeholder for WebContainer/E2B cleanup
            del self.active_sessions[self.session_id]
