import os
import json
import logging
import uuid
import time
from threading import Thread
from typing import Dict, Any, Generator, Optional
from daytona_sdk import Daytona, DaytonaConfig
from daytona_sdk.common.daytona import CreateSandboxFromImageParams
from ..ai.stepfun_client import OpenRouterBuilderClient

logger = logging.getLogger(__name__)

class AgentOrchestrator:
    # Class-level dictionary to hold active sandboxes per session
    # In a real production system, this would be in Redis or DB
    active_sessions: Dict[str, Any] = {}

    def __init__(self, session_id: str = None):
        self.session_id = session_id or str(uuid.uuid4())
        
        self.api_key = os.getenv("DAYTONA_API_KEY")
        self.api_url = os.getenv("DAYTONA_API_URL") or os.getenv("DAYTONA_SERVER_URL")
        self._available = bool(self.api_key and self.api_url)

        if self._available:
            self.config = DaytonaConfig(
                api_key=self.api_key,
                api_url=self.api_url,
                target=os.getenv("DAYTONA_TARGET", "local"),
            )
            self.daytona = Daytona(config=self.config)
        else:
            self.daytona = None

    def _sse(self, payload: dict) -> str:
        return f"data: {json.dumps(payload)}\n\n"

    def get_or_create_sandbox(self):
        """Gets existing sandbox for session, or creates a new one."""
        if not self._available:
            return None

        if self.session_id in self.active_sessions:
            return self.active_sessions[self.session_id]

        logger.info(f"Creating new Daytona sandbox for session {self.session_id}...")
        params = CreateSandboxFromImageParams(
            image="daytonaio/sandbox:0.5.0-slim",
            language="javascript"
        )
        sandbox = self.daytona.create(params)
        self.active_sessions[self.session_id] = sandbox
        return sandbox

    def stream_build(self, prompt: str, model_name: str, existing_files=None, is_chat=False) -> Generator[str, None, None]:
        """
        Orchestrates the real-time AI generation + Daytona build streaming.
        Yields SSE formatted strings.
        """
        yield self._sse({"status": "Initializing agent orchestrator..."})

        # 1. AI Generation Stream
        client = OpenRouterBuilderClient(model=model_name)
        full_raw_text = ""
        generated_files = []
        
        # We reuse the stream_generation from our openrouter client
        # It yields chunk, thinking, progress events directly.
        for event in client.stream_generation(
            prompt, 
            existing_files=existing_files, 
            output_type="react", 
            suppress_done=True
        ):
            if event.startswith("data: "):
                try:
                    payload = json.loads(event[6:].strip())
                    if "files" in payload:
                        generated_files = payload["files"]
                    else:
                        yield event # Forward chunk, thinking, progress
                except json.JSONDecodeError:
                    yield event
            else:
                yield event

        if not generated_files:
            yield self._sse({"error": "No files were generated by the AI."})
            return

        # 2. Upload to Daytona Sandbox
        yield self._sse({"status": "Preparing Daytona Sandbox..."})
        sandbox = self.get_or_create_sandbox()

        if not sandbox:
            yield self._sse({"log": "Warning: Daytona credentials missing. Preview disabled.\n"})
            yield self._sse({"complete": True, "files": generated_files})
            return

        yield self._sse({"status": "Uploading files to workspace..."})
        for file in generated_files:
            # Upload file
            logger.info(f"Uploading {file['name']}...")
            try:
                # Daytona SDK expects bytes for file content
                sandbox.fs.upload_file(file['content'].encode('utf-8'), file['name'])
                yield self._sse({
                    "file_created": file['name'],
                    "action": "modified" if is_chat else "created"
                })
                # Small sleep for visual effect in UI as requested by user flow
                time.sleep(0.1)
            except Exception as e:
                logger.error(f"Failed to upload {file['name']}: {e}")

        if not is_chat:
            # 3. NPM Install
            yield self._sse({"status": "Installing dependencies..."})
            try:
                # The python Daytona SDK's process.exec is synchronous.
                # To stream logs block by block, we would ideally use an async shell stream.
                # However, standard process.exec returns an ExecuteResponse with full 'result'.
                # We'll run it and yield the full log, simulating the real-time stream.
                
                # Note: For true real-time streaming, the Python SDK needs async/WebSocket process execution.
                # We will yield the final install output as a log chunk.
                install_res = sandbox.process.exec("npm install")
                yield self._sse({"log": f"$ npm install\n{install_res.result}\n"})
                
                if install_res.exit_code != 0:
                    yield self._sse({"error": f"Failed to install dependencies (Exit {install_res.exit_code})"})
                    # We still return the files so the user sees the code
                    yield self._sse({"complete": True, "files": generated_files})
                    return
            except Exception as e:
                yield self._sse({"error": f"NPM Install error: {str(e)}"})

            # 4. Start Dev Server
            yield self._sse({"status": "Starting dev server..."})
            
            # We need to start 'npm run dev' asynchronously so it keeps running in the background.
            # process.exec blocks until finish, which we DONT want for a dev server.
            # Alternatively, we can use nohup or & inside the exec.
            # Let's start it in the background:
            try:
                # Kill any existing Vite processes first!
                sandbox.process.exec("npx kill-port 5173")
                
                # Start dev server in the background and redirect output
                sandbox.process.exec("nohup npm run dev -- --host 0.0.0.0 --port 5173 > dev.log 2>&1 &")
                yield self._sse({"log": "$ npm run dev\nServer starting in background...\n"})
                
                # Wait a moment for Vite to start
                time.sleep(2)
                
                # Check dev_log
                log_res = sandbox.process.exec("cat dev.log")
                if log_res.result:
                    yield self._sse({"log": log_res.result + "\n"})

            except Exception as e:
                yield self._sse({"error": f"Dev server error: {str(e)}"})
                yield self._sse({"complete": True, "files": generated_files})
                return

        # Optional: The Daytona preview URL pattern. 
        # In local OSS Daytona, ports are exposed on the host or via a proxy url.
        # The preview URL format depends on the Daytona architecture. 
        # For the SDK, `sandbox.get_workspace_url()` might exist, or we construct it.
        # If using local standard target: port 5173 is exposed.
        
        # Actually, Daytona OSS automatically forwards ports.
        # We'll assume the URL is structured based on the sandbox ID and port.
        # This is a placeholder; consult accurate Daytona SDK docs for port forwarding URLs.
        preview_url = f"http://localhost:5173" # Placeholder - update with correct proxy URL
        
        yield self._sse({
            "complete": True,
            "preview_url": preview_url,
            "summary": "Build successful! Live preview is ready." if not is_chat else "Files updated! Live preview refreshed.",
            "files": generated_files,
            "session_id": self.session_id
        })

    def cleanup(self):
        """Deletes the sandbox and frees resources."""
        if not self._available:
            return
        if self.session_id in self.active_sessions:
            sandbox = self.active_sessions[self.session_id]
            logger.info(f"Cleaning up session {self.session_id} - Sandbox {sandbox.id}")
            try:
                self.daytona.delete(sandbox)
            except Exception as e:
                logger.error(f"Failed to delete Daytona sandbox: {e}")
            del self.active_sessions[self.session_id]
