# Generated by Django 5.2.8 on 2026-03-12 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(default="Untitled Project", max_length=100),
                ),
                ("prompt", models.TextField()),
                (
                    "output_type",
                    models.CharField(
                        choices=[("html", "HTML/CSS/JS"), ("react", "React")],
                        default="html",
                        max_length=10,
                    ),
                ),
                ("style_preset", models.CharField(blank=True, max_length=30)),
                ("files", models.JSONField(default=list)),
                ("explanation", models.TextField(blank=True)),
                ("raw_response", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("credits_used", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generation Session",
                "verbose_name_plural": "Generation Sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
