# Generated by Django 5.2.8 on 2026-03-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0002_generationsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationsession",
            name="conversation",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="file_tree",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="parent_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_sessions",
                to="builder.generationsession",
            ),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
