# Generated by Django 5.2.8 on 2026-04-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0003_generationsession_conversation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationsession",
            name="build_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="build_logs",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="build_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="intent_type",
            field=models.CharField(
                choices=[
                    ("small_talk", "Small Talk"),
                    ("general_help", "General Help"),
                    ("build_new", "Build New"),
                    ("edit_existing", "Edit Existing"),
                    ("fix_error", "Fix Error"),
                    ("unclear", "Unclear"),
                ],
                default="build_new",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="preview_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
