# Generated by Django 5.2.8 on 2026-04-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0004_generationsession_lifecycle_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationsession",
            name="runtime_metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="runtime_provider",
            field=models.CharField(
                choices=[("none", "None"), ("webcontainer", "WebContainer")],
                default="none",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="runtime_session_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="runtime_status",
            field=models.CharField(
                choices=[
                    ("not_ready", "Not Ready"),
                    ("prepared", "Prepared"),
                    ("booting", "Booting"),
                    ("running", "Running"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="not_ready",
                max_length=20,
            ),
        ),
    ]
