# Generated by Django 5.2.8 on 2026-04-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0005_generationsession_runtime_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationsession",
            name="auto_fix_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="verification_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("failed", "Failed"),
                    ("retrying", "Retrying"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
