# Generated by Django 5.2.8 on 2026-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0006_generationsession_verification_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationsession",
            name="design_tokens",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="generationsession",
            name="user_preferences",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="usercredits",
            name="credits",
            field=models.IntegerField(default=200),
        ),
    ]
