# Generated by Django 5.2.6 on 2025-10-26 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('programming', 'Programming'), ('cybersecurity', 'Cybersecurity')], max_length=50)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50)),
                ('environment_type', models.CharField(choices=[('vscode', 'VSCode Online'), ('python', 'Python Sandbox'), ('linux', 'Linux Terminal'), ('ai', 'AI Notebook'), ('web', 'Web Security Lab'), ('network', 'Network Simulation')], default='vscode', max_length=50)),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_labs', to='courses.course')),
            ],
        ),
    ]
